### ISSUE TITLE
License for the library required

### ISSUE THREAD

**Issue by raghav-g** [aacotroneo/laravel-saml2#124]
Hi @aacotroneo ,

The library is great and it seems to works just fine but what is the license used by your library?. If possible could you add a MIT license to it - https://opensource.org/licenses/MIT ?

If there is no license attached then adoption of the library would be impossible without clarification in writing.

**Comment by aacotroneo** [comment]
Hi, good suggestion. yes, it's open source. I'll add the MIT license next week. thanks

**Comment by raghav-g** [comment]
Thanks Alejandro. If you do that I can go ahead and use the library without any worries in any company I work with. Amazing work btw :)

**Comment by aacotroneo** [comment]
Thanks! it's a convenient wrapper that covers the most usual cases :). all
the heavy lifting work is done by one login, which is also MIT so we won't
have any issues there.

I'm not with the computer this week. I'll push the change as soon as i sit
down with git.

El 15 feb. 2018 9:41 a. m., "Raghav Gopalakrishnan" <
notifications@github.com> escribió:

Thanks Alejandro. If you do that I can go ahead and use the library without
any worries in any company I work with. Amazing work btw :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aacotroneo/laravel-saml2/issues/124#issuecomment-365915910>,
or mute the thread

**Comment by raghav-g** [comment]
Awesome thanks!

**Comment by aacotroneo** [comment]
added MIT license :)

**Comment by raghav-g** [comment]
Thanks @aacotroneo ! 👍
