### ISSUE TITLE
Redirect to the URL being viewed

### ISSUE THREAD

**Issue by neomaximus2k** [aacotroneo/laravel-saml2#158]
In laravel, when you use the built in AUTH system, if you visit an address (e.g. http://localhost/this/address/here) and you are not logged on you get redirected back to the logon screen.  However once you logon you get redirect back to the URL you were trying to view (http://localhost/this/address/here)

How can we achieve this with SAML2?

**Comment by aacotroneo** [comment]
you'll have to add some logic on your log-in handler (where you initiate the saml flow). Get the intended URL you need to go back to (referrer?), and pass it to the login function here https://github.com/aacotroneo/laravel-saml2/blob/4c20f49a932f813e722f2ceff308d60c9369ae75/src/Aacotroneo/Saml2/Saml2Auth.php#L60 . 
```Saml2Auth::login(getBackToThisURL)```
It will send it the the IDP, the IDP sends it back as a relayState, and the library redirects there after a successful login (you just do the first step I mentioned)

**Comment by neomaximus2k** [comment]
If I'm reading your post correctly, I should be able to do something like ....

`
$SAMLLogin = new Saml2Auth();
$SAMLLogin->returnTo = Session::get('url.intended', url('/')); //redirect()->intended($this->redirectTo);
$SAMLLogin->login();
`

**Comment by aacotroneo** [comment]
I just linked you to the source code for reference, but you only have to call it.

```
// -- at some place you detect the user is not authenticated - you get the url, and initiate the flow.
Saml2Auth::login($getBackToThisURL)
```

**Comment by neomaximus2k** [comment]
This no longer works and returns an error 

> Non-static method Aacotroneo\Saml2\Saml2Auth::login() should not be called statically

**Comment by darynmitchell** [comment]
The place where you'll need to do some customization is where the login call is made, in Saml2Controller.php:
```php
    public function login()
    {
        $this->saml2Auth->login(config('saml2_settings.loginRoute'));
    }
```

That calls into Saml2Auth::login with just one parameter, a fixed route from config.
You'll want to replace that first argument with the route that you want to redirect to after login.

I haven't done it myself yet but I assume you could achieve this by:
1. Making your own controller that extends Saml2Controller, to customize the login function, and
2. Making your own copy of _aacotroneo\laravel-saml2\src\routes.php_ that points to that new controller, and in your saml2_settings.php config file, turn off `useRoutes`, so that Saml2ServiceProvider doesn't include its built-in route definition file.
