### ISSUE TITLE
No example provided on how to handle the assertion

### ISSUE THREAD

**Issue by MrToxy** [aacotroneo/laravel-saml2#227]
My Idp is redirecting to `/sso/reply` and I'm not able to change this to match to the pre-defined routes of the package.
on the controller, I'm doing:

```
    public function reply(Request $request)
    {
        // SAMLResponse is available in the request
        // $request->SAMLResponse;
        $saml2Auth = new Saml2Auth(Saml2Auth::loadOneLoginAuthFromIpdConfig('test'));

        $user = $saml2Auth->getSaml2User();

        event(new Saml2LoginEvent('test', $user, $saml2Auth));
    }
```

However on  the event listener, the user doesn't have any attributes  and `$messageId = $event->getSaml2Auth()->getLastMessageId();` always comes back as null.

Where is an example of how to programmatically parse the saml response and treat its data?

**Comment by danmichaelo** [comment]
Do you mean that the IDP, after veryifying the user, redirects back to `/sso/reply` on your site instead of `{idp}/acs`? If so, you should be able to manually create a route that points to `Saml2Controller@acs` ála the default one:

https://github.com/aacotroneo/laravel-saml2/blob/master/src/routes.php#L23-L26

Something along the lines of this:

```php
Route::middleware(config('saml2_settings.routesMiddleware'))
    ->group(function() {
        $saml2_controller = config('saml2_settings.saml2_controller', 'Aacotroneo\Saml2\Http\Controllers\Saml2Controller');

        Route::post('/sso/reply', array(
            'as' => 'saml2_acs',
            'uses' => $saml2_controller.'@acs',
        ));

    });
```

You might need to [manually bind](https://laravel.com/docs/7.x/routing#explicit-binding) `idpName` if not provided in the URI

**Comment by MrToxy** [comment]
I was able to solve it
