### ISSUE TITLE
Dynamic idp_host

### ISSUE THREAD

**Issue by Hesesses** [aacotroneo/laravel-saml2#36]
Hello,

Is it possible to use dynamic $idp_host? We would like to get that url from user's settings..

**Comment by aacotroneo** [comment]
`saml2_settings.php` is a php script that returns an array... you can put code in there if you want

**Comment by tsaltena** [comment]
Just as a heads-up for someone looking into this same direction: I had a lot of trouble with Laravel 5.5 caching the configuration file (and therefore ignoring dynamic statements). Fixed it with a manual route that updates the Config before calling the Login event. You shouldn't redirect to the regular login route but call fire the event in the controller, because the config update is only valid for a single request.
